# Generated by Django 4.1.6 on 2023-03-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='feedmain',
            name='rating',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedmain',
            name='review',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
