# Generated by Django 4.1.6 on 2023-03-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_rating_feedmain_rating_feedmain_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedmain',
            name='review',
        ),
    ]
